import {
  Binoculars,
  Bomb,
  Crosshair,
  Flag,
  HeartPulse,
  Helicopter,
  MapPin,
  Package,
  PlaneLanding,
  Radar,
  Shield,
  Skull,
  Swords,
  Tent,
  TriangleAlert,
  Truck,
  Users,
  type LucideIcon,
} from "lucide-react";
import type { MarkerSymbol } from "../markers";

export const markerIcons: Record<MarkerSymbol, LucideIcon> = {
  infantry: Users,
  sniper: Crosshair,
  vehicle: Truck,
  helicopter: Helicopter,
  mortar: Bomb,
  antiair: Radar,
  fob: Tent,
  objective: Flag,
  attack: Swords,
  defend: Shield,
  rally: MapPin,
  lz: PlaneLanding,
  supply: Package,
  medic: HeartPulse,
  observe: Binoculars,
  enemy: Skull,
  danger: TriangleAlert,
};
